/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "text-secondary": "#94A3B8",
        "surface-container": "#171f33",
        "on-secondary": "#003824",
        "surface-hover": "#334155",
        "background": "#0b1326",
        "on-tertiary": "#233144",
        "surface-container-high": "#222a3d",
        "on-error-container": "#ffdad6",
        "surface": "#0b1326",
        "on-secondary-fixed-variant": "#005236",
        "primary-fixed-dim": "#68dba9",
        "on-tertiary-container": "#1c2a3d",
        "surface-container-lowest": "#060e20",
        "outline": "#87948b",
        "tertiary-fixed-dim": "#b9c7e0",
        "tertiary": "#b9c7e0",
        "secondary-fixed-dim": "#4edea3",
        "surface-card": "#1E293B",
        "on-tertiary-fixed-variant": "#3a485c",
        "primary": "#68dba9",
        "text-primary": "#F8FAFC",
        "on-surface": "#dae2fd",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#005137",
        "tertiary-fixed": "#d5e3fd",
        "on-primary-container": "#00311f",
        "inverse-surface": "#dae2fd",
        "tertiary-container": "#8392a9",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#85f8c4",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "primary-container": "#25a475",
        "inverse-primary": "#006c4a",
        "secondary": "#4edea3",
        "on-background": "#dae2fd",
        "outline-variant": "#3d4a42",
        "destructive": "#DC2626",
        "surface-tint": "#68dba9",
        "surface-container-low": "#131b2e",
        "secondary-fixed": "#6ffbbe",
        "border-subtle": "rgba(51, 65, 85, 0.5)",
        "inverse-on-surface": "#283044",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed": "#0d1c2f",
        "on-primary": "#003825",
        "secondary-container": "#00a572",
        "surface-bright": "#31394d",
        "surface-dim": "#0b1326",
        "on-secondary-container": "#00311f",
        "on-surface-variant": "#bccac0",
        "surface-container-highest": "#2d3449"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "gutter-mobile": "16px",
        "stack-md": "16px",
        "gutter-desktop": "24px",
        "container-max": "1280px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "safe": "env(safe-area-inset-bottom)"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "title-lg": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
